Add username to Discord payload
k3rn31p4nic/appveyor-discord-webhook pull request #17
Opened 2023-01-11 06:34 UTC by blackjackkent

Coming back to a project using this webhook after a while; I started getting an error that the `username` value in the Discord payload could not be empty. I updated it in my local copy to use the `$AUTHOR_NAME` variable and it seems to work fine now. :)

2023-01-11 06:46 UTC, iamtraction commented
when you create a webhook in discord, you can set the username there. you don't have to set it here. the `username` field here is only used to override the default username you set in discord. or is it not the case anymore?

2023-01-11 06:49 UTC, blackjackkent commented
It seems like the Discord webhook processing doesn't like that value to be set to an empty string anymore. With the current script, the request to Discord gets rejected.

2023-01-13 22:19 UTC, iamtraction requested changes

2023-01-13 22:19 UTC, iamtraction commented on send.ps1
> +  ""username"": ""$AUTHOR_NAME"",
Ref https://github.com/DiscordHooks/gitlab-ci-discord-webhook/pull/11

```suggestion
```

2023-01-13 22:23 UTC, merged